"""ReviewComment schema for code review in frontend workflow."""

from datetime import datetime
from typing import Optional, List
from enum import Enum
from pydantic import BaseModel, Field


class ReviewSeverity(str, Enum):
    """Severity of a review comment."""
    BLOCKER = "blocker"  # Must fix before merge
    MAJOR = "major"      # Should fix before merge
    MINOR = "minor"      # Nice to have
    SUGGESTION = "suggestion"  # FYI


class ReviewCategory(str, Enum):
    """Category of review comment."""
    CODE_QUALITY = "code_quality"
    PERFORMANCE = "performance"
    ACCESSIBILITY = "accessibility"
    TESTING = "testing"
    SECURITY = "security"
    CONVENTION = "convention"
    DESIGN_TOKEN = "design_token"
    API_INTEGRATION = "api_integration"
    ERROR_HANDLING = "error_handling"


class ReviewComment(BaseModel):
    """
    Single code review comment generated by code_review agent.

    Identifies issues and provides actionable feedback on code quality,
    accessibility, testing, token violations, API handling, etc.
    """

    id: str = Field(..., description="Comment identifier")
    line_number: Optional[int] = Field(default=None, description="Line number (if applicable)")
    file_path: Optional[str] = Field(default=None, description="File path (if applicable)")

    # Review content
    severity: ReviewSeverity = Field(..., description="Severity level")
    category: ReviewCategory = Field(..., description="Category of issue")
    title: str = Field(..., description="Short title of issue")
    message: str = Field(..., description="Detailed message")

    # Actionable feedback
    suggested_fix: Optional[str] = Field(
        default=None,
        description="Suggested code fix or improvement"
    )
    reference_url: Optional[str] = Field(
        default=None,
        description="Link to documentation or pattern (e.g., design system, WCAG, eslint rule)"
    )

    # Related components/tests
    component_id: Optional[str] = Field(default=None)
    test_file_id: Optional[str] = Field(default=None)

    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    resolved: bool = Field(default=False)

    def to_markdown(self) -> str:
        """Convert to human-readable Markdown."""
        severity_emoji = {
            ReviewSeverity.BLOCKER: "🔴",
            ReviewSeverity.MAJOR: "🟠",
            ReviewSeverity.MINOR: "🟡",
            ReviewSeverity.SUGGESTION: "🔵",
        }

        lines = [
            f"{severity_emoji.get(self.severity, '❓')} **{self.severity.value.upper()}** - {self.category.value}",
            f"**{self.title}**",
        ]

        if self.line_number and self.file_path:
            lines.append(f"`{self.file_path}:{self.line_number}`")

        lines.extend(["", self.message])

        if self.suggested_fix:
            lines.extend([
                "",
                "**Suggested Fix:**",
                "```",
                self.suggested_fix,
                "```",
            ])

        if self.reference_url:
            lines.extend(["", f"**Reference:** {self.reference_url}"])

        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "line_number": self.line_number,
            "file_path": self.file_path,
            "severity": self.severity.value,
            "category": self.category.value,
            "title": self.title,
            "message": self.message,
            "suggested_fix": self.suggested_fix,
            "reference_url": self.reference_url,
            "component_id": self.component_id,
            "test_file_id": self.test_file_id,
            "created_at": self.created_at.isoformat(),
            "resolved": self.resolved,
        }
